import type { Reservation } from "../types/reservation.types";

export const mockReservations: Reservation[] = [
  {
    id: "1",
    guest: "Margaret Wanjiru",
    guestNo: "GH-1024",
    guestPhone: "+254 712 345 678",
    accommodation: "Deluxe Room 204",
    stay: "24 Jul - 27 Jul",
    checkInDate: "2026-07-24",
    checkOutDate: "2026-07-27",
    adults: 2,
    children: 0,
    nights: 3,
    totalAmount: 36000,
    paidAmount: 36000,
    balanceAmount: 0,
    amount: "KES 36,000",
    payment: "Paid",
    paymentMethod: "M-Pesa",
    payments: [
      {
        id: "payment-1",
        amount: 36000,
        method: "M-Pesa",
        status: "Completed",
        receiptNumber: "RCT-1001",
        transactionReference: "MPESA-ABC123",
        notes: null,
        paidAt: "2026-07-24T10:30:00Z",
      },
    ],
    notes: "Guest requested a quiet room.",
    source: "Direct",
    status: "Checked In",
  },
  {
    id: "2",
    guest: "John Mwangi",
    guestNo: "GH-1025",
    guestPhone: "+254 723 456 789",
    accommodation: "Cottage 3",
    stay: "Today",
    checkInDate: "2026-07-24",
    checkOutDate: "2026-07-25",
    adults: 2,
    children: 1,
    nights: 1,
    totalAmount: 18500,
    paidAmount: 10000,
    balanceAmount: 8500,
    amount: "KES 18,500",
    payment: "Partial",
    paymentMethod: "Cash",
    payments: [
      {
        id: "payment-2",
        amount: 10000,
        method: "Cash",
        status: "Completed",
        receiptNumber: "RCT-1002",
        transactionReference: null,
        notes: null,
        paidAt: "2026-07-24T09:15:00Z",
      },
    ],
    notes: "",
    source: "Walk-in",
    status: "Reserved",
  },
  {
    id: "3",
    guest: "Sarah Kimani",
    guestNo: "GH-1026",
    guestPhone: "+254 734 567 890",
    accommodation: "Camping Site 5",
    stay: "Tomorrow",
    checkInDate: "2026-07-25",
    checkOutDate: "2026-07-27",
    adults: 2,
    children: 0,
    nights: 2,
    totalAmount: 8000,
    paidAmount: 0,
    balanceAmount: 8000,
    amount: "KES 8,000",
    payment: "Pending",
    paymentMethod: "Pending",
    payments: [],
    notes: "Guest will arrive in the afternoon.",
    source: "Online",
    status: "Pending",
  },
  {
    id: "4",
    guest: "Peter Otieno",
    guestNo: "GH-1027",
    guestPhone: "+254 745 678 901",
    accommodation: "Conference Hall A",
    stay: "26 Jul",
    checkInDate: "2026-07-26",
    checkOutDate: "2026-07-26",
    adults: 20,
    children: 0,
    nights: 1,
    totalAmount: 45000,
    paidAmount: 45000,
    balanceAmount: 0,
    amount: "KES 45,000",
    payment: "Paid",
    paymentMethod: "Bank Transfer",
    payments: [
      {
        id: "payment-4",
        amount: 45000,
        method: "Bank Transfer",
        status: "Completed",
        receiptNumber: "RCT-1004",
        transactionReference: "BANK-TRX-1004",
        notes: null,
        paidAt: "2026-07-23T14:20:00Z",
      },
    ],
    notes: "Corporate conference booking.",
    source: "Corporate",
    status: "Checked Out",
  },
];