export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  RESERVATIONS: "/reservations",
  ROOMS: "/rooms",
  GUESTS: "/guests",
  RESTAURANT: "/restaurant",
  KITCHEN: "/kitchen",
  BAR: "/bar",
  CONFERENCE: "/conference",
  CAMPING: "/camping",
  ACTIVITIES: "/activities",
  HOUSEKEEPING: "/housekeeping",
  INVENTORY: "/inventory",
  REPORTS: "/reports",
  USERS: "/users",
  SETTINGS: "/settings",
} as const;